language: cpp
addons:
  apt:
    packages:
      - libncurses-dev
      - make
      - g++
compiler:
  - clang
  - gcc
install: true
script: make
notifications:
  slack: tornsphinx:Dexg5USrFdOVasbUji6SsLgP
travis encrypt "tornsphinx:Dexg5USrFdOVasbUji6SsLgP" --add notifications.slack
